### ISSUE TITLE
Comprehensive User Guide

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#96]
**What would you like to be added**:

Add a user guide including all the details of command line argument, especially for the object store.

**Why is this needed**:

People may find it difficult to connect JuiceFS with some object store, for example, Ceph, we should have a guide on how to specify the arguments for every object store we support.

### Backlog

- [x] Command reference #119 #122 
- [x] How to setup different object storage #135 #162 
- [x] Best practice to deploy Redis #171 #174 #177 
- [x] Comparison with other projects #179 
- [x] Hadoop SDK user guide #141 #144 #149 #150 #154 #167
- [x] How to auto-mount JuiceFS #163 
- [x] Use JuiceFS on K8s #184 #191
- [x] Cache management #193
- [x] Fault diagnosis and analysis #197 
- [x] Monitoring and Grafana template #202 
- [x] S3 gateway #203 
- [x] More FAQs #198 
- [x] FUSE mount options #215
- [x] Windows client #271
